---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-project
  labels:
    kubernetes.io/metadata.name: demo-project
  annotations:
    openshift.io/display-name: RHDH demo project
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: demo-project-group
  namespace: demo-project
spec:
  targetNamespaces:
    - demo-project
