apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: keycloak-postgres-pvc
  namespace: demo-project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: keycloak-postgres
  namespace: demo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgres
  template:
    metadata:
      labels:
        app: keycloak-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: password
          volumeMounts:
            - name: postgres-storage
              mountPath: /data
              subPath: postgres-data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: keycloak-postgres-pvc
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: keycloak-db-secret
  namespace: demo-project
type: Opaque
data:
  password: YXZlcnlzZWN1cmVwYXNzd29yZA== # TODO change this value
  username: a2V5Y2xvYWs=
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: keycloak-postgres
  namespace: demo-project
spec:
  selector:
    app: keycloak-postgres
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
