apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhdh
  namespace: rhdh-operator
  labels:
    operators.coreos.com/rhdh.rhdh-operator: ''
  annotations:
    olm.operatorGroup: rhdh-operator
    rhdh.openshift.io/display-name: "Red Hat Developer Hub"
spec:
  channel: fast
  installPlanApproval: Automatic
  name: rhdh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhdh-operator.v1.5.1
