apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-plugins-rhdh
  namespace: demo-project
  labels:
    rhdh.redhat.com/ext-config-sync: "true"
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: './dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic'
        disabled: false
      - package: './dynamic-plugins/dist/backstage-community-plugin-topology'
        disabled: false
      - package: './dynamic-plugins/dist/backstage-plugin-kubernetes'
        disabled: false
      - package: './dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic'
        disabled: false
      - package: './dynamic-plugins/dist/backstage-community-plugin-redhat-argocd'
        disabled: false
