---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhdh-k8s-sa
  namespace: demo-project
---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-k8s-sa-token
  namespace: demo-project
  annotations:
    kubernetes.io/service-account.name: rhdh-k8s-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhdh-k8s-sa-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: rhdh-k8s-sa
    namespace: demo-project
