apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devhub-deploy
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: rhdh
    repoURL: https://github.com/ysoni-redhat/RHDH-Phase2.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - CreateNamespace=true
